### ISSUE TITLE
Login "loop" with IfModule check

### ISSUE THREAD

**Issue by jdpurdyvi** [michaelryanmcneill/shibboleth#64]
For whatever reason adding the `<IfModule mod_shib>` block in b4ecfbbfbf02ec715564a3ea109c6e506961a5d2 to resolve #60 sends some my installations into a situation where the SAMLPost loops back on itself. 

Easy enough to avoid by adding `define('SHIBBOLETH_DISALLOW_FILE_MODS', true);` to wp-config.php but thought it was worth a mention.

These are on a cPanel shared webhost so it might be an edge case.

**Comment by dandalpiaz** [comment]
I'm experiencing this as well. Also on a cPanel host.

**Comment by michaelryanmcneill** [comment]
Interesting...can either of you look what the module is called in your PHP configuration and see if it is named something else? I will go ahead and release an emergency patch version that reverts #60 until we find a better solution.

**Comment by michaelryanmcneill** [comment]
Just released version 2.2.1 of the plugin that reverts this change. Should be live on WordPress.org momentarily. I'd like to know what the name of the cPanel Shibboleth module is that PHP sees so that ideally, we could add an additional conditional to allow the default implementation to work out of the box @jdpurdyvi @dandalpiaz.

**Comment by michaelryanmcneill** [comment]
Closing this and reopening #60 so that we can do additional work there.

**Comment by dandalpiaz** [comment]
Thanks for the quick update! I'm checking with the folks who have full access to our cPanel server to see about the module name / why that conditional isn't working. Will follow-up when I hear back.
